# Generated by Django 4.2 on 2023-04-21 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('age_from', models.SmallIntegerField(blank=True, null=True, verbose_name='Вік з')),
                ('age_to', models.SmallIntegerField(blank=True, null=True, verbose_name='Вік по')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Запис створено')),
                ('all_places', models.SmallIntegerField(default=0, verbose_name='Кількість місць')),
                ('free_places', models.SmallIntegerField(default=0, verbose_name='Вільних місць')),
                ('description', models.TextField(verbose_name='Про секцію')),
            ],
            options={
                'verbose_name': 'Спортивна секція',
                'verbose_name_plural': 'Спортивні секції',
            },
        ),
        migrations.CreateModel(
            name='Sportsman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('firstname', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True, verbose_name='По батькові')),
                ('birthdate', models.DateField(verbose_name='Дата народження')),
                ('gender', models.CharField(choices=[('', 'не обрано'), ('m', 'чол'), ('f', 'жін')], default='', max_length=1, verbose_name='Стать')),
                ('detail', models.TextField(verbose_name='Про спортсмена')),
            ],
        ),
        migrations.CreateModel(
            name='SectionSportsman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='Почав займатись з')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Закінчив займатись')),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.section')),
                ('sportsman_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.sportsman')),
            ],
            options={
                'verbose_name': 'Спортсмен секції',
                'verbose_name_plural': 'Спортсмени секції',
            },
        ),
        migrations.CreateModel(
            name='EnrollmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('firstname', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True, verbose_name='По батькові')),
                ('birthdate', models.DateField(verbose_name='Дата народження')),
                ('gender', models.CharField(choices=[('', 'не обрано'), ('m', 'чол'), ('f', 'жін')], default='', max_length=1, verbose_name='Стать')),
                ('status', models.SmallIntegerField(choices=[(0, 'не обрана'), (1, 'нова'), (2, 'на розгляді'), (3, 'погоджено'), (4, 'відмовлено')], default=0, verbose_name='Статус заявки')),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.section')),
            ],
            options={
                'verbose_name': 'Заявка на запис до секції',
                'verbose_name_plural': 'Заявкм на запис до секції',
            },
        ),
    ]
