# Generated by Django 4.2 on 2023-04-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollmentrequest',
            options={'verbose_name': 'Заявка на запис до секції', 'verbose_name_plural': 'Заявки на запис до секції'},
        ),
        migrations.AlterModelOptions(
            name='sportsman',
            options={'verbose_name': 'Спортсмен', 'verbose_name_plural': 'Спортсмени'},
        ),
        migrations.AddField(
            model_name='enrollmentrequest',
            name='chat_id',
            field=models.PositiveIntegerField(default=0, verbose_name='chat id'),
        ),
        migrations.AlterField(
            model_name='sportsman',
            name='detail',
            field=models.TextField(blank=True, null=True, verbose_name='Про спортсмена'),
        ),
    ]
